version: 2

jobs:
  test_backend:
    docker:
      - image: cimg/node:17.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: package install process
          command: yarn
      - save_cache:
          paths:
            - ~repo/node_modules
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: yarn test
          command: yarn test:ci

workflows:
  version: 2
  workflows_backend:
    jobs:
      - test_backend
